services:
  # A Docker web service
  - type: web
    name: pulse-backend
    env: docker
    repo: https://github.com/mike-paper/pulse.git # optional
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    branch: master # optional (uses repo default)
    dockerfilePath: ./backend/Dockerfile
    # dockerCommand: . 
    dockerContext: ./backend
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /ping
    envVars:
      - key: WORKERS
        value: 4
      - key: PORT
        value: 5000
      - fromGroup: pulse
  # A static site
  - type: web
    env: static
    name: pulse-frontend
    repo: https://github.com/mike-paper/pulse.git
    branch: master # optional (uses repo default)
    buildCommand: cd frontend && yarn add @vue/cli-service && yarn build
    staticPublishPath: frontend/dist
    pullRequestPreviewsEnabled: true # optional
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /old
        destination: /new
      - type: rewrite
        source: /a/*
        destination: /a